### ISSUE TITLE
Unable to execute schematics generate commands

### ISSUE THREAD

**Issue by daniel-zero** [angular-architects/nx-ddd-plugin#94]
I added the plugin to my package.json and tried to execute the generate domain command using the console and the nx console plugin in my project. I also created a new nx angular workspace. Each of this ways results in the following errors in the console

```bash
> Executing task: npx nx generate @angular-architects/ddd:domain --name=watchlist --no-interactive --dry-run <

[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] An Angular builder called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
SchematicsException [Error]: Project "watchlist-domain" does not exist.
    at /home/daniel/workspace/zero/zero-frontend/node_modules/@schematics/angular/component/index.js:100:19
SchematicsException [Error]: Project "watchlist-domain" does not exist.
    at /home/daniel/workspace/zero/zero-frontend/node_modules/@schematics/angular/component/index.js:100:19
Project "watchlist-domain" does not exist.
The terminal process "bash '-c', 'npx nx generate @angular-architects/ddd:domain --name=watchlist --no-interactive --dry-run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by wizardnet972** [comment]
I can confirm this.

```

  Node : 16.13.0
  OS   : darwin arm64
  yarn : 1.22.11

  nx : 13.3.0
  @nrwl/angular : 13.3.1
  @nrwl/cli : 13.3.0
  @nrwl/cypress : 13.3.0
  @nrwl/devkit : 13.3.0
  @nrwl/eslint-plugin-nx : 13.3.0
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0
  @nrwl/linter : 13.3.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.1
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0
  @nrwl/storybook : 13.3.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.0
  	 @angular/common: 13.1.0
  	 @angular/compiler: 13.1.0
  	 @angular/core: 13.1.0
  	 @angular/forms: 13.1.0
  	 @angular/platform-browser: 13.1.0
  	 @angular/platform-browser-dynamic: 13.1.0
  	 @angular/router: 13.1.0
  	 @ngrx/component-store: 13.0.2
  	 @ngrx/effects: 13.0.2
  	 @ngrx/entity: 13.0.2
  	 @ngrx/router-store: 13.0.2
  	 @ngrx/store: 13.0.2
  	 @angular-architects/ddd: 1.5.1
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular/cdk: 13.1.0
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.1.0
  	 @angular/language-service: 13.1.0
  	 @angular/material: 13.1.0
  	 @jscutlery/semver: 2.15.0
  	 @ngneat/input-mask: 5.0.1
  	 @ngneat/scam: 3.0.4
  	 @ngrx/data: 13.0.2
  	 @ngrx/schematics: 13.0.2
  	 @ngrx/store-devtools: 13.0.2
  	 @rx-angular/template: 1.0.0-beta.29
  	 @storybook/angular: 6.4.9
  	 nx-stylelint: 13.1.0

```

**Comment by dc-p8** [comment]
Had the same issue. Update nx by running this command `nx migrate latest && npm install` solved the issue for me.
```diff
- "@nrwl/angular": "13.3.0",
+ "@nrwl/angular": "13.3.2",
```

**Comment by wizardnet972** [comment]
The problem  still exists:
"@angular-architects/ddd@^1.5.1"
"@nrwl/angular@^13.3.4"

```
SchematicsException [Error]: Project "auth-feature-login" does not exist.
    at /Users/wizardnet972/code/nx-ddd/node_modules/@schematics/angular/component/index.js:100:19
```

**Comment by manfredsteyer** [comment]
The next version will fix this. Will be there soon.
