### ISSUE TITLE
Data path "" must NOT have additional properties(style) in v1.5.1

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#97]
Run:
```
yarn nx g @angular-architects/ddd:domain --name=bla --dry-run
```

Got:
```
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"domain","directory":"bla","tags":"domain:bla,type:domain-logic","style":"scss","prefix":"bla","publishable":false,"buildable":true}
Errors:

  Data path "" must NOT have additional properties(style).
    at MapSubscriber.project (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:143:22)
    at ThrowIfEmptySubscriber._next (/Users/wizardnet972/code/nx-ddd/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
Schematic input does not validate against the Schema: {"name":"domain","directory":"bla","tags":"domain:bla,type:domain-logic","style":"scss","prefix":"bla","publishable":false,"buildable":true}
Errors:

  Data path "" must NOT have additional properties(style).
error Command failed with exit code 1.
```

**Comment by manfredsteyer** [comment]
Thanks for the poiner and for the fix. This issue comes up with Nx 13.x.

We will publish a new version soon (version 2.0.x) for Nx 13.
